import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    // this ignore default title if use use absolute
    absolute:"",
    // default title (This is the default title for all loyout without metadata)
    default:"Next app",
    // dynamic title
    template:"%s | sky education"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <div className="bg-gray-200"> 

        {children}
        </div>
        <Footer/>
        </body>
    </html>
  );
}
